In [38]:
import pandas as pd
from influxdb import InfluxDBClient
from influxdb import SeriesHelper
from influxdb import DataFrameClient
import datetime
import matplotlib.pyplot as plt

In [2]:
host = '183.136.205.102'
port = 38086
user = 'root'
password = 'root'
dbname = 'chq'

In [67]:
# myclient = InfluxDBClient(host, port, user, password, 'market')
# myclient.create_database('market')
# myclient.create_retention_policy('inf_policy', 'INF', 1, default=True)
# client = DataFrameClient(host, port, user, password, 'challenge')
# client.query('drop measurement "idx.positon"')

ResultSet({})

## 指数行情

In [13]:
market_dbname = 'market'
market_series_name = "index.day"
market_client = DataFrameClient(host, port, user, password, market_dbname)

### 更新指数行情

In [14]:
filename = "idx_market.csv"
def get_index_market_per_day(filename):
    idx_market = pd.read_csv(filename, dtype={'ticker':str, 'name': str}, parse_dates=['date'])
    idx_market = idx_market.drop('Unnamed: 0', axis=1)
    idx_market = idx_market.set_index('date')
    return idx_market

In [15]:
idx_market = get_index_market_per_day(filename)
idx_market.head()

,ticker,name,pre_close,open,low,high,close
date,,,,,,,
2017-10-09,000016,上证50,2672.3272,2736.8345,2688.5382,2743.3643,2692.0769
2017-10-10,000016,上证50,2692.0769,2693.2510,2671.9426,2711.3065,2695.5374
2017-10-09,000300,沪深300,3836.5013,3910.1149,3876.0322,3918.8391,3882.2076
2017-10-10,000300,沪深300,3882.2076,3883.0037,3855.4666,3900.7418,3889.8637
2017-10-09,000905,中证500,6603.2587,6682.5774,6657.5305,6696.6664,6678.3710

In [16]:
market_client.write_points(idx_market, market_series_name, tag_columns=['ticker', 'name'], field_columns=['pre_close', 'open', 'low', 'high', 'close'])

True

### 获取指数行情

In [17]:
df = market_client.query('select * from  "{0}"'.format(market_series_name))
market = df[series_name]
market.tail()

,close,high,low,name,open,pre_close,ticker
2017-10-09 00:00:00+00:00,3882.2076,3918.8391,3876.0322,沪深300,3910.1149,3836.5013,000300
2017-10-09 00:00:00+00:00,6678.3710,6696.6664,6657.5305,中证500,6682.5774,6603.2587,000905
2017-10-10 00:00:00+00:00,3889.8637,3900.7418,3855.4666,沪深300,3883.0037,3882.2076,000300
2017-10-10 00:00:00+00:00,6705.4812,6705.7177,6658.8617,中证500,6677.3723,6678.3710,000905
2017-10-10 00:00:00+00:00,2695.5374,2711.3065,2671.9426,上证50,2693.2510,2692.0769,000016

### 更新仓位信息

In [56]:
files = ['0926', '0927', '0928', '0929', '1009', '1010'] #文件{%m%d}.csv
def get_positions(files):
    all_pos = pd.DataFrame()
    for file in files:
        pos = pd.read_csv('position/{0}.csv'.format(file), encoding='gbk')
        pos = pos.rename(columns={"Unnamed: 0": 'user'})
        pos = pos.dropna(how='all', axis=1).dropna(how='all', axis=0)
        pos['date'] = datetime.datetime.strptime('2017{0}'.format(file), "%Y%m%d")
        all_pos = pd.concat([all_pos, pos])
    all_pos = all_pos.fillna(0)
    all_pos = all_pos.set_index(['date', 'user'])
    all_pos = all_pos.stack()
    all_pos = all_pos.reset_index().set_index('date')
    all_pos.columns = ['user', 'name', 'position']
    return all_pos

In [57]:
new_pos = get_positions(files)

In [58]:
new_pos

           user   name  position
date
2017-09-26  陈红青   上证50       0.0
2017-09-26  陈红青  沪深300       0.0
2017-09-26  陈红青  中证500       0.0
2017-09-26  许小强   上证50       0.5
2017-09-26  许小强  沪深300       0.0
2017-09-26  许小强  中证500       0.0
2017-09-26   肖灿   上证50       0.5
2017-09-26   肖灿  沪深300       0.3
2017-09-26   肖灿  中证500       0.3
2017-09-26  严龙灿   上证50       0.8
2017-09-26  严龙灿  沪深300       0.0
2017-09-26  严龙灿  中证500       0.1
2017-09-26   张超   上证50       0.6
2017-09-26   张超  沪深300       0.0
2017-09-26   张超  中证500       0.3
2017-09-26  陈康康   上证50       0.6
2017-09-26  陈康康  沪深300       0.0
2017-09-26  陈康康  中证500       0.5
2017-09-26  刘一奇   上证50       0.4
2017-09-26  刘一奇  沪深300       0.0
2017-09-26  刘一奇  中证500       0.0
2017-09-26  朱奕杰   上证50       0.8
2017-09-26  朱奕杰  沪深300       0.0
2017-09-26  朱奕杰  中证500       0.0
2017-09-26   孙洋   上证50       0.7
2017-09-26   孙洋  沪深300       0.2
2017-09-26   孙洋  中证500       0.6
2017-09-26  徐柱杨   上证50       0.0
2017-09-26  徐柱杨  沪深300       0.0
2017-09-26  徐柱杨  中证500       0.0
...         ...    ...       ...
2017-10-10  严龙灿   上证50       0.3
2017-10-10  严龙灿  沪深300       0.0
2017-10-10  严龙灿  中证500       0.0
2017-10-10   张超   上证50       0.6
2017-10-10   张超  沪深300       0.0
2017-10-10   张超  中证500       0.0
2017-10-10  陈康康   上证50       0.2
2017-10-10  陈康康  沪深300       0.2
2017-10-10  陈康康  中证500       0.2
2017-10-10  刘一奇   上证50       0.4
2017-10-10  刘一奇  沪深300       0.0
2017-10-10  刘一奇  中证500       0.0
2017-10-10  朱奕杰   上证50       0.0
2017-10-10  朱奕杰  沪深300       0.0
2017-10-10  朱奕杰  中证500       0.2
2017-10-10   孙洋   上证50       0.3
2017-10-10   孙洋  沪深300       0.0
2017-10-10   孙洋  中证500       0.0
2017-10-10  徐柱杨   上证50       0.3
2017-10-10  徐柱杨  沪深300       0.1
2017-10-10  徐柱杨  中证500       0.0
2017-10-10   苗苗   上证50       0.3
2017-10-10   苗苗  沪深300       0.0
2017-10-10   苗苗  中证500       0.0
2017-10-10  张金生   上证50       0.3
2017-10-10  张金生  沪深300       0.0
2017-10-10  张金生  中证500       0.0
2017-10-10  肖鹏懿   上证50       0.3
2017-10-10  肖鹏懿  沪深300       0.5
2017-10-10  肖鹏懿  中证500       0.0

[234 rows x 3 columns]

In [59]:
challenge_dbname = "challenge"
pos_series_name = "idx.position"
# myclient = InfluxDBClient(host, port, user, password, dbname)
# myclient.create_database(dbname)
# myclient.create_retention_policy('inf_policy', 'INF', 1, default=True)
challenge_client = DataFrameClient(host, port, user, password, challenge_dbname)

In [60]:
challenge_client.write_points(new_pos, pos_series_name, tag_columns=['user', 'name'], field_columns=['position'])

True

### 获取仓位信息

In [61]:
df = client.query('select * from  "{0}"'.format(pos_series_name))

In [62]:
all_pos = df[pos_series_name]

In [65]:
all_pos.tail()

                            name  position user
2017-10-10 00:00:00+00:00  中证500       0.0  陈红青
2017-10-10 00:00:00+00:00  中证500       0.0  肖鹏懿
2017-10-10 00:00:00+00:00  沪深300       0.2   肖灿
2017-10-10 00:00:00+00:00   上证50       0.2  陈康康
2017-10-10 00:00:00+00:00  中证500       0.0   孙洋

### 计算净值

In [28]:
def cal_return(x):
    return ((x['close'] - x['open']) * x['position'] + (x['open'] - x['pre_close']) * x['pre_position'])  / x['pre_close']

In [29]:
dbname = "challenge"
challenge_client = DataFrameClient(host, port, user, password, dbname)

In [30]:
def cal_returns(position, market):
    return_series_name = "idx.return"
    for user in position.user.unique():
        for idx_name in position.name.unique():
            user_idx = position[(position['user']==user) & (position['name'] == idx_name)].copy()
            user_idx['pre_position'] = user_idx['position'].shift(1)
            user_idx = user_idx.fillna(0)
            market_idx = market[market['name']==idx_name]
            profit = pd.merge(user_idx, market_idx, left_index=True, right_index=True, on='name')
            profit['profit'] = profit.apply(cal_return, axis=1)
            profit['profit'] = profit['profit'] + 1
            profit['return'] = profit['profit'].cumprod()
            challenge_client.write_points(profit, return_series_name, tag_columns=['user', 'name', 'ticker'], field_columns=['profit', 'return'])

In [43]:
all_pos.tail()

                           name  position user
2017-09-26 00:00:00+00:00  上证50       0.0  徐柱杨
2017-09-26 00:00:00+00:00  上证50       0.2  张金生
2017-09-26 00:00:00+00:00  上证50       0.6   张超
2017-09-26 00:00:00+00:00  上证50       0.7   孙洋
2017-09-26 00:00:00+00:00  上证50       0.4  刘一奇

In [32]:
market.tail()

,close,high,low,name,open,pre_close,ticker
2017-10-09 00:00:00+00:00,3882.2076,3918.8391,3876.0322,沪深300,3910.1149,3836.5013,000300
2017-10-09 00:00:00+00:00,6678.3710,6696.6664,6657.5305,中证500,6682.5774,6603.2587,000905
2017-10-10 00:00:00+00:00,3889.8637,3900.7418,3855.4666,沪深300,3883.0037,3882.2076,000300
2017-10-10 00:00:00+00:00,6705.4812,6705.7177,6658.8617,中证500,6677.3723,6678.3710,000905
2017-10-10 00:00:00+00:00,2695.5374,2711.3065,2671.9426,上证50,2693.2510,2692.0769,000016

In [33]:
cal_returns(all_pos, market)

### 获取净值信息

In [36]:
return_series_name = "idx.return"
df = challenge_client.query('select * from  "{0}"'.format(return_series_name))
returns = df[return_series_name]
returns.tail()

                           name    profit    return  ticker user
2017-09-26 00:00:00+00:00  上证50  1.000000  1.000000  000016  徐柱杨
2017-09-26 00:00:00+00:00  上证50  1.000406  1.000406  000016  张金生
2017-09-26 00:00:00+00:00  上证50  1.001219  1.001219  000016   张超
2017-09-26 00:00:00+00:00  上证50  1.001422  1.001422  000016   孙洋
2017-09-26 00:00:00+00:00  上证50  1.000813  1.000813  000016  刘一奇

In [40]:
for key, grp in returns.groupby(['name', 'user']):
    plt.plot(grp['profit'], label=key)
#     grp['D'] = pd.rolling_mean(grp['B'], window=5)    
#     plt.plot(grp['D'], label='rolling ({k})'.format(k=key))
plt.legend(loc='best')    
plt.show

In [41]:
returns

                            name    profit    return  ticker user
2017-09-26 00:00:00+00:00   上证50  1.001625  1.001625  000016  严龙灿
2017-09-26 00:00:00+00:00  沪深300  1.000000  1.000000  000300  陈红青
2017-09-26 00:00:00+00:00  沪深300  1.000000  1.000000  000300  陈康康
2017-09-26 00:00:00+00:00  沪深300  1.000000  1.000000  000300  许小强
2017-09-26 00:00:00+00:00  沪深300  1.000000  1.000000  000300   苗苗
2017-09-26 00:00:00+00:00  沪深300  1.000274  1.000274  000300  肖鹏懿
2017-09-26 00:00:00+00:00  沪深300  1.000821  1.000821  000300   肖灿
2017-09-26 00:00:00+00:00  沪深300  1.000000  1.000000  000300  朱奕杰
2017-09-26 00:00:00+00:00  沪深300  1.000000  1.000000  000300  徐柱杨
2017-09-26 00:00:00+00:00  沪深300  1.000000  1.000000  000300  张金生
2017-09-26 00:00:00+00:00  沪深300  1.000000  1.000000  000300   张超
2017-09-26 00:00:00+00:00  沪深300  1.000547  1.000547  000300   孙洋
2017-09-26 00:00:00+00:00  沪深300  1.000000  1.000000  000300  刘一奇
2017-09-26 00:00:00+00:00  沪深300  1.000000  1.000000  000300  严龙灿
2017-09-26 00:00:00+00:00  中证500  1.000000  1.000000  000905  陈红青
2017-09-26 00:00:00+00:00  中证500  1.002803  1.002803  000905  陈康康
2017-09-26 00:00:00+00:00  中证500  1.000000  1.000000  000905  许小强
2017-09-26 00:00:00+00:00  中证500  1.000000  1.000000  000905   苗苗
2017-09-26 00:00:00+00:00  中证500  1.000561  1.000561  000905  肖鹏懿
2017-09-26 00:00:00+00:00  中证500  1.001682  1.001682  000905   肖灿
2017-09-26 00:00:00+00:00  中证500  1.000000  1.000000  000905  朱奕杰
2017-09-26 00:00:00+00:00  中证500  1.000000  1.000000  000905  徐柱杨
2017-09-26 00:00:00+00:00  中证500  1.000000  1.000000  000905  张金生
2017-09-26 00:00:00+00:00  中证500  1.001682  1.001682  000905   张超
2017-09-26 00:00:00+00:00  中证500  1.003363  1.003363  000905   孙洋
2017-09-26 00:00:00+00:00  中证500  1.000000  1.000000  000905  刘一奇
2017-09-26 00:00:00+00:00  中证500  1.000561  1.000561  000905  严龙灿
2017-09-26 00:00:00+00:00   上证50  1.000000  1.000000  000016  陈红青
2017-09-26 00:00:00+00:00   上证50  1.001219  1.001219  000016  陈康康
2017-09-26 00:00:00+00:00   上证50  1.001016  1.001016  000016  许小强
2017-09-26 00:00:00+00:00   上证50  1.001016  1.001016  000016   苗苗
2017-09-26 00:00:00+00:00   上证50  1.001422  1.001422  000016  肖鹏懿
2017-09-26 00:00:00+00:00   上证50  1.001016  1.001016  000016   肖灿
2017-09-26 00:00:00+00:00   上证50  1.001625  1.001625  000016  朱奕杰
2017-09-26 00:00:00+00:00   上证50  1.000000  1.000000  000016  徐柱杨
2017-09-26 00:00:00+00:00   上证50  1.000406  1.000406  000016  张金生
2017-09-26 00:00:00+00:00   上证50  1.001219  1.001219  000016   张超
2017-09-26 00:00:00+00:00   上证50  1.001422  1.001422  000016   孙洋
2017-09-26 00:00:00+00:00   上证50  1.000813  1.000813  000016  刘一奇